Copy attrs keys to avoid "dictionary changed size during iteration".
Python 3 `dict.keys()` returns a view of the dictionary’s keys,
not a copy as Python 2. Deleting keys while iterating the view will cause
```
RuntimeError: dictionary changed size during iteration
```
PiperOrigin-RevId: 414454586