Possible repro for #455
See #455 for overall scenario. These minimal-ish changes cause the
following stack trace if you launch the basic app and click on the
"fizz" button.

```
05-26 13:32:58.269  1150  1178 E ActivityControllerCore: java.lang.NoSuchMethodError: No virtual method convert(Ljava/time/Duration;)J in class Ljava/util/concurrent/TimeUnit; or its super cl
asses (declaration of 'java.util.concurrent.TimeUnit' appears in /apex/com.android.art/javalib/core-oj.jar)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at com.basicapp.basicdep.BasicDep.toLong(Unknown Source:4)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at com.basicapp.basicdep.BasicDep.toString(Unknown Source:0)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at com.basicapp.BasicActivity$1.onClick(Unknown Source:35)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.view.View.performClick(View.java:7448)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.view.View.performClickInternal(View.java:7425)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.view.View.access$3600(View.java:810)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.view.View$PerformClick.run(View.java:28305)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.os.Handler.handleCallback(Handler.java:938)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.os.Handler.dispatchMessage(Handler.java:99)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.os.Looper.loop(Looper.java:223)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at android.app.ActivityThread.main(ActivityThread.java:7656)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at java.lang.reflect.Method.invoke(Native Method)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-26 13:32:58.269  1150  1178 E ActivityControllerCore:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Repro command:
```
bazelisk build java/com/basicapp:basic_app --nodesugar_java8_libs && \
  adb install bazel-bin/java/com/basicapp/basic_app.apk && \
  adb logcat
```