Merge #245 by Bencodes: Update r8.bzl to return AndroidPreDexJarInfo
This provider is missing on the android_binary target when R8 is enabled which is needed later by the application.bzl rule.

```
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_android~/rules/android_application/android_application_rule.bzl", line 387, column 29, in _impl
                ctx.attr.base_module[AndroidPreDexJarInfo],
Error: <target //apps/rider:bin_devRelease> (rule 'android_binary') doesn't contain declared provider 'AndroidPreDexJarInfo'
```
Closes #245
COPYBARA_INTEGRATE_REVIEW=https://github.com/bazelbuild/rules_android/pull/245 from Bencodes:patch-10 631f3ed23cbeb4becd48402bf4ac86050a7b9876
PiperOrigin-RevId: 651058410
Change-Id: I433b17667bdd91fc3773cf9298cc29ceb156c02e